language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow 500 --allow-dupe --allow-redirect --allow-ssl --white-list mp.weixin.qq.com,www.vaikan.com,www.kawabangga.com,worktile.com,http://www.ifanr.com/646923,https://zhuanlan.zhihu.com/p/19724078,https://segmentfault.com/jobs/search?remote=1
